#!/bin/bash

cat >> .env << EOF
APP_NAME=${APP_NAME}
APP_DESC=${APP_DESC}
SIGNUP_DISABLED=${SIGNUP_DISABLED}
ENABLE_CLUSTER_MODE=${ENABLE_CLUSTER_MODE}
SUBDOMAINS_DISABLED=${SUBDOMAINS_DISABLED}
SESSION_SECRET=${SESSION_SECRET}
PORT=${PORT}
SOCKET_PORT=${SOCKET_PORT}

# Create first user
CREATE_ADMIN=${CREATE_ADMIN}
CREATE_ADMIN_ACCOUNT=${CREATE_ADMIN}
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_USERNAME=${ADMIN_USERNAME}
ADMIN_PASSWORD=${ADMIN_PASSWORD}

# Environment=
NODE_ENV=${NODE_ENV}

# Analytics
GOOGLE_ANALYTICS_ID=${GOOGLE_ANALYTICS_ID}
PRERENDER_TOKEN=${PRERENDER_TOKEN}
COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN}
DSN_KEY=${DSN_KEY}
RAVEN_DSN=${RAVEN_DSN}
reCAPTCHA_KEY=${reCAPTCHA_KEY}

# Social Accounts
FACEBOOK_ID=${FACEBOOK_ID}
FACEBOOK_SECRET=${FACEBOOK_SECRET}

TWITTER_KEY=${TWITTER_KEY}
TWITTER_SECRET=${TWITTER_SECRET}

GOOGLE_ID=${GOOGLE_ID}
GOOGLE_SECRET=${GOOGLE_SECRET}

LINKEDIN_ID=${LINKEDIN_ID}
LINKEDIN_SECRET=${LINKEDIN_SECRET}

GITHUB_ID=${GITHUB_ID}
GITHUB_SECRET=${GITHUB_SECRET}

 # Mail configmail=
MAILER_EMAIL_ID=${MAILER_EMAIL_ID}
MAILER_PASSWORD=${MAILER_PASSWORD}
MAILER_FROM=${MAILER_FROM}

# Use this for one of Nodemailer's pre-configured service providers
MAILER_SERVICE_PROVIDER=${MAILER_SERVICE_PROVIDER}

# Use these for a custom service provider 
# Note=MAILER_SMTP_HOST will override MAILER_SERVICE_PROVIDER
# MAILER_SMTP_HOST=${MAILER_SMTP_HOST}
# MAILER_SMTP_PORT=${MAILER_SMTP_PORT}
# MAILER_SMTP_SECURE=${MAILER_SMTP_SECURE}
REDIS_DB_PORT_6379_TCP_ADDR=${REDIS_DB_PORT_6379_TCP_ADDR}
REDIS_DB_PORT_6379_TCP_PORT=${REDIS_DB_PORT_6379_TCP_PORT}
DB_PORT_27017_TCP_ADDR=${DB_PORT_27017_TCP_ADDR}
DB_HOST=${DB_HOST}
BASE_URL=${BASE_URL}

ROOT=${ROOT}

# Mailu version to run (stable, 2.0, 2.1, etc. or latest)
VERSION=${VERSION}
# # Set to what environment you will be running TellForm in (production or development)
# NODE_ENV=production

# Set to a randomly generated 16 bytes string
SECRET_KEY=${SECRET_KEY}

# # URI of Mongo database that TellForm will connect to
MONGODB_URI=${MONGODB_URI}

# # URL Redis server that TellForm will connect to
REDIS_URL=${REDIS_URL}

# Address where listening ports should bind
BIND_ADDRESS=${BIND_ADDRESS}

# Main domain that TellForm will be hosted at
DOMAIN=${DOMAIN}

# Set this to server your websockets server on a seperate URL
SOCKETS_URL=${SOCKETS_URL}

EOF

node server.js
#pm2 start process.yml
